name: Run Style Tests
on:
  - push

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: true
          use-isort: true
          python-root-list: "pytils"
